# Generated by Django 5.1.5 on 2025-01-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_name',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
